### ISSUE TITLE
Unable to verify your data submission

### ISSUE THREAD

**Issue by klytron** [TonisOrmisson/yii2-address-form#1]
I get the error whenever the form tries to load the cities.

investigating the error 

POST http://example.com/addressform/query/regions

form data 

```
depdrop_parents[0] : "GH"
depdrop_all_params[address-country]: "GH"
```

Request Payload:

`depdrop_parents%5B0%5D=GH&depdrop_all_params%5Baddress-country%5D=GH`

Response:
```

{
    "name": "Bad Request",
    "message": "Unable to verify your data submission.",
    "code": 0,
    "status": 400,
    "type": "yii\\web\\BadRequestHttpException"
}

```

what could cause the error?

using "yiisoft/yii2": "2.0.38",

**Comment by klytron** [comment]
I realise that updating `tonisormisson\addressform\controllers\QueryController`  

with `$this->enableCsrfValidation = false; `

solved the error

```
class QueryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function init()
    {
        parent::init();
        \Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
    }

    public function beforeAction($action)
    {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * @return array
     */
    public function actionRegions()
    {
```

**Comment by TonisOrmisson** [comment]
Seems like more probably a more general problem in your app configuration. You should not need to turn off `enableCsrfValidation` for this. Works for me with `enableCsrfValidation`  anyway. Maybe related to some https://github.com/kartik-v/yii2-widget-depdrop/pull/72 not sure.

**Comment by TonisOrmisson** [comment]
closing this as it seems not related to this package.
